#!/bin/bash
set -euo pipefail

OUT="${SRCROOT}/KoKo/Generated/BuildTimestamp.swift"
mkdir -p "$(dirname "$OUT")"

DATE_PART="$(date '+%Y%m%d')"
TIME_PART="$(date '+%H:%M:%S')"

cat > "$OUT" <<EOF
// Auto-generated by Scripts/generate_build_timestamp.sh — do not edit.
enum BuildTimestamp {
    static let dateTimeSuffix = "${DATE_PART}${TIME_PART}"
}
EOF
